exclude: ['README.md']
include: ['_pages']

defaults:
  -
    scope:
      path: '_posts'
    values:
      layout: 'default'
      is_post: true

object_store:
  - https://mk-cdn.freetls.fastly.net

image_store:
  - https://mk-cdn.freetls.fastly.net/ep/

plugins:
  - jekyll-feed
