exclude: ['README.md']
include: ['_pages']

defaults:
  -
    scope:
      path: '_posts'
    values:
      layout: 'episode'

object_store:
  - https://mk-cdn.freetls.fastly.net

image_store:
  - https://mk-cdn.freetls.fastly.net/ep/

plugins:
  - jekyll-feed

timezone: UTC

author:
  name: Toru Maesaka
  uri: https://twitter.com/tmaesaka
