exclude: ['README.md']
include: ['_pages']

defaults:
  -
    scope:
      path: '_posts'
    values:
      layout: 'default'
      is_post: true

image_bucket: 'https://mk-cdn.global.ssl.fastly.net'
